### ISSUE TITLE
Enum: Fields in nested structs of struct variants  cannot be renamed if the name contains a colon?

### ISSUE THREAD

**Issue by Dgame** [media-io/yaserde#59]
```rust
#[derive(Debug, YaSerialize)]
pub struct Root {
    #[yaserde(rename = "MyVariant")]
    pub variant: Variant,
}

#[derive(Debug, YaSerialize)]
pub enum Variant {
    #[yaserde(rename = "MyFoo")]
    Foo {
        #[yaserde(rename = "such:Test")]
        test: Test,
    },
    #[yaserde(rename = "MyBar")]
    Bar {
        #[yaserde(rename = "ID")]
        id: String,
    },
}

#[derive(Debug, YaSerialize)]
pub struct Test {
    #[yaserde(rename = "my:Test")]
    pub test: bool,
}

let r = request::Root {
    variant: request::Variant::Foo {
        test: request::Test { test: false },
    },
};
println!("{:?}", yaserde::ser::to_string(&r));
```

panics with `"such:Test" is not a valid identifier`. If I remove the `such:` it works fine.

**Comment by Dgame** [comment]
If I use `#[yaserde(prefix = "such", rename = "Test")]` it compiles. But I've got the same problem as mentioned in #60.

**Comment by MarcAntoine-Arnaud** [comment]
In XML `prefix:` refers to a specific namespace.
Using prefix attribute will be usefull for de-serializing because the namespace can have a totally different prefix, you don't have to take about which prefix is use, just the related namespace.

So it's a good point to receive an error here, to disable this kind of usage.
Are you agreed ?

**Comment by MarcAntoine-Arnaud** [comment]
I close it, reopen if needed.

**Comment by Dgame** [comment]
> Are you agreed ?

Yes
